---

# połaczenia do serwerów będą realizowane 
# przy pomocy AWS SSM, co umożliwia dostęp nawet do maszyn,
# które znajdują się w prywatnych sieciach
ansible_connection: aws_ssm
ansible_aws_ssm_region: eu-central-1

# bucket potrzebny dla 
# https://docs.ansible.com/ansible/latest/collections/community/aws/aws_ssm_connection.html
ansible_aws_ssm_bucket_name: praca-inz-ansible-bucket

ansible_python_interpreter: /usr/bin/python3