---

- hosts: all
  gather_facts: true
  become: true
  roles:
   - { role: yum }
   - { role: ntp, when: ntp__configure, tags: ['ntp'] }

- hosts: jenkins
  gather_facts: true
  become: true
  tags:
    - jenkins
  roles:
   - { role: jenkins }

- hosts: symfony_app
  gather_facts: true
  become: true
  tags:
    - symfony
    - symfony_app
  roles:
   - { role: php }
   - { role: apache2 }
