---

- hosts: all
  gather_facts: true
  become: true
  roles:
   - { role: yum }
   - { role: ntp, when: ntp__configure, tags: ['ntp'] }

- hosts: symfony_app
  gather_facts: true
  become: true
  tags:
    - symfony
    - symfony_app
    - app
  roles:
  #  - { role: php }
   - { role: apache2 }

- hosts: jenkins
  gather_facts: true
  become: true
  tags:
    - jenkins
  roles:
   - { role: jenkins }

- hosts:
    - percona_partkeepr
  gather_facts: true
  become: true
  tags:
    - db
    - percona
  roles:
   - { role: percona }
