---

- hosts: all
  become: true
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
  roles:
   - { role: yum }
   - { role: ntp, when: ntp__configure, tags: ['ntp'] }

- hosts: partkeepr_app
  gather_facts: false
  become: true
  tags:
    - symfony
    - partkeepr
    - app
  roles:
   - { role: nodejs }
   - { role: php }
   - { role: apache2 }

- hosts: partkeepr_lb
  gather_facts: false
  become: true
  tags:
    - haproxy
    - lb
    - partkeepr
    - app
  roles:
   - { role: haproxy }

- hosts:
    - percona_partkeepr
  gather_facts: false
  become: true
  tags:
    - db
    - percona
  roles:
   - { role: percona }

- hosts: jenkins
  gather_facts: false
  become: true
  tags:
    - jenkins
  roles:
   - { role: jenkins }
