---

# Ten playbook jest uruchamiany przy stawianiu maszyny wirtualnej 
# jenkinsa w AWS, dlatego ma `connection: local`

- name: Install and configure local Jenkins
  hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  tasks:
    - include_role: { name: jenkins }, when: true
