---

#
# Przy uruchamianiu lokalnie host nie jest w grupie "jenkins", dlatego w normalnych
# warunkach ustawienia jakie są skonfigurowane nie będą ładowane.
# Trick polega na tym, że w repozytorium znajduje się symlink host_vars/localhost -> group_vars/jenkins
# dzięki czemu wszystkie ustawienia są zgodne
# 
- name: Install and configure local Jenkins
  hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  tasks:
    - include_role: { name: jenkins }
