---

apache__mods_enabled:
  - rewrite
  - ssl
  - proxy
  - proxy_fcgi

apache__virtualhosts:
  - servername: "partkeepr"
    serveralias: "*"
    documentroot: /var/www/partkeepr/current/public
    extra_parameters: |
      <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm-pool.sock|fcgi://localhost/"
      </FilesMatch>
  
      ErrorLog logs/partkeepr-error.log
      CustomLog logs/partkeepr-access.log combined
