---

apache__mods_enabled:
  - rewrite
  - proxy
  - proxy_fcgi

apache__virtualhosts:
  - servername: "partkeepr"
    serveralias: "*"
    documentroot: /var/www/partkeepr/current/public
    extra_documentroot_parameters: |
      DirectoryIndex index.php

      <IfModule mod_negotiation.c>
        Options -MultiViews
      </IfModule>

      <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_URI}::$0 ^(/.+)/(.*)::\2$
        RewriteRule .* - [E=BASE:%1]

        # Sets the HTTP_AUTHORIZATION header removed by Apache
        RewriteCond %{HTTP:Authorization} .+
        RewriteRule ^ - [E=HTTP_AUTHORIZATION:%0]

        # Removes the /index.php/ part from a URL, if present
        RewriteCond %{ENV:REDIRECT_STATUS} =""
        RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

        # If the requested filename exists, simply serve it.
        # Otherwise rewrite all other queries to the front controller.
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ %{ENV:BASE}/index.php [L]
      </IfModule>
    extra_parameters: |
      <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm-pool.sock|fcgi://localhost/"
      </FilesMatch>
  
      ErrorLog logs/partkeepr-error.log
      CustomLog logs/partkeepr-access.log combined
