---

- name: Import nodesource rpm key
  rpm_key:
    key: http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version | int < 7

- name: Add nodesource repository
  yum:
    name: "http://rpm.nodesource.com/pub_{{ nodejs__version }}/el/7/{{ ansible_architecture }}/nodesource-release-el7-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version | int < 7
  register: node_repo

- name: Disable Node.js AppStream module
  command: yum module disable -y nodejs
  register: module_disable
  changed_when: "'Nothing to do.' not in module_disable.stdout"
  when: ansible_distribution_major_version | int >= 8

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs-{{ nodejs__version | regex_replace('x', '') }}*"
    state: present
    enablerepo: nodesource
