---

- name: Import nodesource rpm key
  rpm_key:
    key: http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version | int < 7

- name: Install NodeJS
  yum:
    name: "https://rpm.nodesource.com/pub_{{ nodejs__version | split('.') | first }}.x/el/7/x86_64/nodejs-{{ nodejs__version }}-1nodesource.x86_64.rpm"
    state: present
