---

# frontend to cześć, która nasłuchuje na zapytania
haproxy__frontend_name: test_frontend
haproxy__frontend_bind_address: "*"
haproxy__frontend_port: 80

# a backend to serwery odbierające ruch
# do których kieruje je load balancer
haproxy__backend_name: test_backend
haproxy__backend_balance_method: roundrobin
haproxy__backend_httpchk: "HEAD / HTTP/1.1\\r\\nHost:localhost"

haproxy__backend_servers: []
# - name: node1
#   address: 10.10.0.1
# - name: node2
#   address: 10.10.0.2

