---

# Defines the version
percona__xtradb_version: "57"

# Data directory
percona__xtradb_datadir: /var/lib/mysql

# Defines the user used
percona__xtradb_mysql_user: mysql

# setup cookie
xtradb_configured: "{{ xtradb_confdir }}/_configured"

# secure cookie
xtradb_secured: "{{ xtradb_confdir }}/_secured"

# password changed cookie
xtradb_password_changed: "{{ xtradb_confdir }}/_password_changed"

#ansible_host Defnes the root user
percona__root_user: root

# Defines the root password
percona__root_password: root

# Define Ansible group in which the nodes exist to be part of the cluster
percona__nodes_group: ansible-nodes

# Define the node pool 

# Defines the service systemd
percona__xtradb_service: mysql

# Defines the network interfaces used
percona__xtradb_bind_interface: eth0

# Defines the network address used
percona__xtradb_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + percona__xtradb_bind_interface]['ipv4']['address'] }}"

# Defines the sst user
percona__sst_user: sstuser

# Defines the sst password
percona__sst_password: sstpassword

# Defines the cluster name
percona__cluster_name: foo

# Defines the swappiness by node
xtradb_swappiness: 0

# Defines users to create
percona__users: []

# Defines databases to create
percona__databases: []

xtradb_binlog_format: "ROW"
xtradb_character_set_server: "utf8"
xtradb_collation_server: "utf8_general_ci"
xtradb_default_storage_engine: "InnoDB"
xtradb_innodb_autoinc_lock_mode: 2
xtradb_innodb_buffer_pool_instances: ""
xtradb_innodb_buffer_pool_size: ""
xtradb_innodb_file_format: ""
xtradb_innodb_file_format_check: ""
xtradb_innodb_file_per_table: ""
xtradb_innodb_flush_log_at_trx_commit: ""
xtradb_innodb_log_buffer_size: ""
xtradb_innodb_log_file_size: ""
xtradb_innodb_strict_mode: "on"
xtradb_join_buffer_size: ""
xtradb_log_warnings: ""
xtradb_long_query_time: ""
xtradb_max_allowed_packet: ""
xtradb_max_connections: "4096"
xtradb_max_heap_table_size: ""
xtradb_max_user_connections: ""
xtradb_pxc_strict_mode: "ENFORCING"
xtradb_query_cache_size: ""
xtradb_read_buffer_size: ""
xtradb_read_rnd_buffer_size: ""
xtradb_skip_name_resolve: "1"
xtradb_slow_query_log: "0"
xtradb_socket: ""
xtradb_sort_buffer_size: ""
xtradb_table_definition_cache: ""
xtradb_table_open_cache: ""
xtradb_table_open_cache_instances: ""
xtradb_tmp_table_size: ""
