---

percona__version_major: "5"
percona__version_minor: "7"
percona__mysql_version: "{{ percona__version_major }}.{{ percona__version_minor }}"

percona__root_password: "pass"
percona__listen_port: "3306"
percona__bind_addr: "127.0.0.1"
percona__mysql_language: "/usr/share/mysql/"
percona__mysql_datadir: "/var/lib/mysql"

percona__mysql_databases: []
percona__mysql_users: []

percona__cluster_mode: false
percona__cluster_name: 'Test cluster'
percona__cluster_hosts: []
percona__cluster_sst_username: sstuser
percona__cluster_sst_password: changeme

# Fine tuning
# mysql_key_buffer: "16M"
# mysql_max_allowed_packet: "256M"
# mysql_thread_stack: "192K"
# mysql_cache_size: "8"
# mysql_myisam_recover: "BACKUP"
# mysql_max_connections: "500"
# mysql_table_cache: "64"
# mysql_thread_concurrency: "10"
# mysql_query_cache_limit: "1M"
# mysql_query_cache_size: "16M"
# mysql_character_set_server: "utf8"
# mysql_collation_server: "utf8_general_ci"
# mysql_mysqldump_max_allowed_packet: "128M"
# mysql_isamchk_key_buffer: "16M"
# mysql_sort_buffer_size: "256K"

# InnoDB tuning
# mysql_innodb_file_per_table: "1"
# mysql_innodb_flush_method: "fdatasync"
# mysql_innodb_buffer_pool_size: "256M"
# mysql_innodb_flush_log_at_trx_commit: "1"
# mysql_innodb_lock_wait_timeout: "50"
# mysql_innodb_log_buffer_size: "1M"
# mysql_innodb_log_file_size: "64M"

# mysql_character_set_client_handshake: "FALSE"

# mysql_timezone_info: "false"

install_rpm_repositories: "true"

# To disable log_bin in percona >=8, enabled by default
mysql_disable_log_bin: "true"

# Default Auth Plugin
# used in templates when Percona Server >= 5.7
mysql_default_authentication_plugin: "mysql_native_password"
