---

percona__version: "57"

percona__datadir: /var/lib/mysql
percona__mysql_user: mysql

# grupa ansible, które zlepiane są w klaster percony
percona__nodes_group: ansible-nodes

# interfejs po którym baza się komunikuje
percona__bind_interface: eth0

# pierwsze node traktowany jako master
percona__master_node: "{{ hostvars[ groups[percona__nodes_group][0] ].ansible_default_ipv4.address }}"

# nazwa klastra
percona__cluster_name: pxc-cluster

# wewnętrzny user wykorzystywany do komunikacji w klastrze
percona__sst_user: sstuser
percona__sst_password: sstpassword

# dane uzytkownika root
percona__root_user: root
percona__root_password: root

# uzytkownicy i bazy
percona__users: []
percona__databases: []

# limit polaczen do bazy
percona__max_connections: "128"