---

- name: Add Percona repository
  yum_repository:
    name: percona-release
    description: Percona repository
    baseurl: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    gpgkey: https://www.percona.com/downloads/percona-release/RPM-GPG-KEY-percona
    gpgcheck: yes

- name: Install Percona server
  yum:
    name: percona-server-server
    state: present
    
- name: "Load timezone database into MySQL"
  shell: "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql"
  