# roles/ansible-role-XtraDB-Cluster/tasks/main.yml
---

- name: Checking if XtraDB cluster is already configured
  stat:
    path: "{{ percona__confmark_configured }}"
  register: "_percona__confmark_configured"

- name: Cheking if XtraDB cluster is already secured
  stat:
    path: "{{ percona__confmark_secured }}"
  register: "_percona__confmark_secured"

- name: Cheking if XtraDB cluster is already configured with the password
  stat:
    path: "{{ percona__confmark_root_password }}"
  register: "_percona__confmark_root_password"

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == 'enabled'

- name: Add Percona yum repository
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Enable Percona repository 
  command: "percona-release setup pxc-{{ percona__version }}"
  changed_when: false

- name: "Install percona database server"
  yum:
    name: "{{ xtradb__packages }}"
    state: present

- name: Start service for the first time
  service:
    name: mysql
    state: started
    enabled: true
  when:
    - not _percona__confmark_secured.stat.exists

- name: include secure tasks
  import_tasks: secure_install.yml
  when:
    - not _percona__confmark_secured.stat.exists

- name: include bootstrap tasks
  import_tasks: bootstrap.yml
  when:
    - not _percona__confmark_configured.stat.exists

- name: include postinstall tasks
  import_tasks: postinstall.yml
  when:
    - percona__bind_address == percona__master_node
