---

- block:
    - name: "Parse temporary password from mysql log, getting last one"
      shell: "cat /var/log/mysqld.log | sed -n 's/.*temporary password is generated for root@localhost: //p' | tail -n1"
      register: temppass

    - name: Set root password
      shell: 'mysql -e "SET PASSWORD = ''{{ percona__root_password }}'';" --connect-expired-password -uroot -p"{{ temppass.stdout }}"'

    - name: Configure root password profile
      template:
        src: root-my-cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600

    - name: Marking as password is changed
      file:
        path: "{{ percona__confmark_root_password }}"
        state: "touch"
        owner: root
        group: root
        mode: '0400'
  when:
    - _percona__confmark_root_password.stat.exists == false

- name: Delete anonymous connections
  mysql_user:
    login_user: "{{ percona__root_user }}"
    login_password: "{{ percona__root_password }}"
    name: ""
    host_all: yes
    state: absent

- name: "Secure the MySQL root user for localhost"
  mysql_user:
    login_user: "{{ percona__root_user }}"
    login_password: "{{ percona__root_password }}"
    name: "{{ percona__root_user }}"
    host: "{{ item }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    - "{{ percona__xtradb_bind_address }}"


- name: Remove the MySQL test database
  mysql_db:
    db: test
    login_user: "{{ percona__root_user }}"
    login_password: "{{ percona__root_password }}"
    state: absent


- name: Marking as secured
  file:
    path: "{{ percona__confmark_secured }}"
    state: "touch"
    owner: root
    group: root
    mode: '0400'

...
