---

- name: Download Plugin Installation Manager Tool
  get_url:
    url: "{{ jenkins__plugin_manager_download_url }}"
    dest: "{{ jenkins__plugin_manager_jar }}"
    mode: 0755

- name: Create plugins template
  template:
    src: plugins.txt.j2
    dest: /var/lib/jenkins/plugins.txt
    mode: 0644
    owner: jenkins
    group: jenkins
  notify: restart jenkins

- name: Install plugins
  shell: "/usr/bin/java -jar {{ jenkins__plugin_manager_jar }} --war /usr/share/java/jenkins.war --plugin-download-directory /var/lib/jenkins/plugins --plugin-file /var/lib/jenkins/plugins.txt"
  changed_when: false

- name: Fix plugins permissions
  shell: chown -R jenkins:jenkins /var/lib/jenkins/plugins
  changed_when: false
