---

# ścieżki do katalogów
percona__confdir: /etc/percona-xtradb-cluster.conf.d
percona__config_file: "{{ percona__confdir }}/wsrep.cnf"

# w tych plikach ansible zapisuje stan
# aby wiedzieć czy dana operacja została już wykonana
percona__confmark_configured: "{{ percona__confdir }}/_configured"
percona__confmark_secured: "{{ percona__confdir }}/_secured"
percona__confmark_root_password: "{{ percona__confdir }}/_password_changed"

# wszystkie IP nodów w klastrze
percona__xtradb_wsrep_cluster_address: "gcomm://{{ groups[percona__nodes_group] | map('extract', hostvars, ['ansible_' ~ percona__xtradb_bind_interface, 'ipv4', 'address']) | join(',') }}"
percona__xtradb_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + percona__xtradb_bind_interface]['ipv4']['address'] }}"

# paczki jakie muszą zostać zainstalowane
xtradb__packages:
  - "Percona-XtraDB-Cluster-{{ percona__xtradb_version }}"
  - MySQL-python
