---

percona__xtradb_wsrep_cluster_address: "gcomm://{{ groups[percona__nodes_group] | map('extract', hostvars, ['ansible_' ~ percona__xtradb_bind_interface, 'ipv4', 'address']) | join(',') }}"
percona__xtradb_master_node: "{{ hostvars[ groups[percona__nodes_group][0] ].ansible_default_ipv4.address }}"

xtradb_repo_filename: "percona"
xtradb_repo_name: "percona-release-$basearch"
xtradb_repo_desc: "Percona-Release YUM repository - $basearch"
xtradb_repo_baseurl: "http://repo.percona.com/release/$releasever/RPMS/$basearch"
xtradb_repo_gpgkey: "https://www.percona.com/downloads/RPM-GPG-KEY-percona"
xtradb_repo_enabled: yes
xtradb_repo_gpgcheck: yes

xtradb_wsrep_provider: /usr/lib64/galera3/libgalera_smm.so
xtradb_confdir: /etc/percona-xtradb-cluster.conf.d
xtradb_config_file: "{{ xtradb_confdir }}/wsrep.cnf"

xtradb_packages:
  - "Percona-XtraDB-Cluster-{{ percona__xtradb_version }}"
  - MySQL-python
