---

percona__xtradb_wsrep_cluster_address: "gcomm://{{ groups[percona__nodes_group] | map('extract', hostvars, ['ansible_' ~ percona__xtradb_bind_interface, 'ipv4', 'address']) | join(',') }}"
percona__xtradb_master_node: "{{ hostvars[ groups[percona__nodes_group][0] ].ansible_default_ipv4.address }}"

xtradb_wsrep_provider: /usr/lib64/galera3/libgalera_smm.so
xtradb_confdir: /etc/percona-xtradb-cluster.conf.d
xtradb_config_file: "{{ xtradb_confdir }}/wsrep.cnf"

xtradb_packages:
  - "Percona-XtraDB-Cluster-{{ percona__xtradb_version }}"
  - MySQL-python
