---

- name: Load php vars
  include_vars: "vars/php-{{ php__version }}.yml"

- name: Install repositories
  include_role:
    name: yum
  vars:
    yum__packages: "{{ php__yum_reposources }}"

- name: Install php packages
  include_role:
    name: yum
  vars:
    yum__packages: "{{ php__yum_packages }}"
    yum__enablerepo: "{{ php__yum__enablerepo }}"
    yum__disablerepo: "{{ php__yum_disablerepo }}"

- name: Install additional php packages
  include_role:
    name: yum
  vars:
    yum__packages: "{{ [php__package_prefix + '-'] | product(php__additional_packages) | map('join') | list }}"
    yum__enablerepo: "{{ php__yum__enablerepo }}"
    yum__disablerepo: "{{ php__yum_disablerepo }}"

- name: Remove default PHP-FPM pool
  file:
    path: "{{ php__fpm_d_directory }}/www.conf"
    state: absent

- name: Configure PHP-FPM pools
  template:
    src: fpm-pool.conf.j2
    dest: "{{ php__fpm_d_directory }}/{{ item.pool_name }}.conf"
  with_items:
    - "{{ php__fpm_pools }}"

- name: Create php alternative
  alternatives:
    name: php
    link: /usr/bin/php
    path: /usr/bin/php{{ php__package_prefix }}
    state: auto

# - name: Install dnf-plugins
#   package:
#     name: dnf-plugins-core
#     state: present

# - name: Enable DNF module for CentOS 8+.
#   shell: |
#     dnf config-manager --set-enabled powertools
#     dnf module enable -y php:remi-{{ php_version }}
#   register: dnf_module_enable
#   changed_when: "'Nothing to do' not in dnf_module_enable.stdout"
