---

- name: Install yum packages
  yum:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ yum__packages }}"
 
- name: Install dnf-plugins
  package:
    name: dnf-plugins-core
    state: present
  when: yum__repositories | length

- name: Configure yum repositories
  yum_repository:
    name: "{{ item.name | default(item) }}"
    enabled: "{{ item.state | ternary(true, false, true) }}"
  with_items: "{{ yum__repositories }}"
