---

- name: Install yum packages
  yum:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ yum__packages }}"
 
- name: Install yum-utils
  package:
    name: yum-utils
    state: present
  when: yum__repositories | length

- name: Disable yum repositories
  yum:
    name: "sos"
    disablerepo: "{{ item.name }}"
  when: "item.state == 'disabled'"
  with_items: "{{ yum__repositories }}"

- name: Enable yum repositories
  yum:
    name: "sos"
    enablerepo: "{{ item.name }}"
  when: "item.state == 'enabled'"
  with_items: "{{ yum__repositories }}"
